export const manufacturers = [
  "Toyota",
  "Honda",
  "Ford",
  "Chevrolet",
  "Nissan",
  "Bmw"
  ];
  
  export const yearsOfProduction = [
    { title: "Year", value: "" },
    { title: "2015", value: "2015" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
  ];
  
  export const fuels = [
    {
      title: "Fuel",
      value: "",
    },
    {
      title: "Gas",
      value: "Gas",
    },
    {
      title: "Electricity",
      value: "Electricity",
    },
  ];
  
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];

  export const cars=[
    {
      "city_mpg": 18,
      "class": "midsize car",
      "combination_mpg": 21,
      "cylinders": 4,
      "displacement": 2.2,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 26,
      "make": "toyota",
      "model": "camry",
      "transmission": "a",
      "year": 1993
    },
    {
      "city_mpg": 22,
      "class": "compact car",
      "combination_mpg": 25,
      "cylinders": 4,
      "displacement": 1.8,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 31,
      "make": "toyota",
      "model": "corolla",
      "transmission": "a",
      "year": 1998
    },
    {
      "city_mpg": 19,
      "class": "compact SUV",
      "combination_mpg": 22,
      "cylinders": 4,
      "displacement": 2.0,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 25,
      "make": "toyota",
      "model": "rav4",
      "transmission": "a",
      "year": 2002
    },
    {
      "city_mpg": 16,
      "class": "pickup truck",
      "combination_mpg": 19,
      "cylinders": 6,
      "displacement": 3.4,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 21,
      "make": "toyota",
      "model": "tacoma",
      "transmission": "m",
      "year": 2000
    },
    {
      "city_mpg": 48,
      "class": "compact car",
      "combination_mpg": 50,
      "cylinders": 4,
      "displacement": 1.5,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 52,
      "make": "toyota",
      "model": "prius",
      "transmission": "a",
      "year": 2005
    },
    {
      "city_mpg": 25,
      "class": "compact car",
      "combination_mpg": 28,
      "cylinders": 4,
      "displacement": 1.6,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 35,
      "make": "honda",
      "model": "civic",
      "transmission": "m",
      "year": 2003
    },
    {
      "city_mpg": 20,
      "class": "midsize car",
      "combination_mpg": 24,
      "cylinders": 4,
      "displacement": 2.4,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 32,
      "make": "honda",
      "model": "accord",
      "transmission": "a",
      "year": 2001
    },
    {
      "city_mpg": 21,
      "class": "compact SUV",
      "combination_mpg": 25,
      "cylinders": 4,
      "displacement": 2.4,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 30,
      "make": "honda",
      "model": "crv",
      "transmission": "a",
      "year": 2004
    },
    {
      "city_mpg": 17,
      "class": "minivan",
      "combination_mpg": 20,
      "cylinders": 6,
      "displacement": 3.5,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 25,
      "make": "honda",
      "model": "odyssey",
      "transmission": "a",
      "year": 1999
    },
    {
      "city_mpg": 16,
      "class": "midsize SUV",
      "combination_mpg": 19,
      "cylinders": 6,
      "displacement": 3.5,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 22,
      "make": "honda",
      "model": "pilot",
      "transmission": "a",
      "year": 2005
    },
    {
      "city_mpg": 24,
      "class": "compact car",
      "combination_mpg": 27,
      "cylinders": 4,
      "displacement": 2.0,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 34,
      "make": "ford",
      "model": "focus",
      "transmission": "m",
      "year": 2004
    },
    {
      "city_mpg": 19,
      "class": "midsize car",
      "combination_mpg": 22,
      "cylinders": 4,
      "displacement": 2.5,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 29,
      "make": "ford",
      "model": "fusion",
      "transmission": "a",
      "year": 2003
    },
    {
      "city_mpg": 16,
      "class": "midsize SUV",
      "combination_mpg": 19,
      "cylinders": 6,
      "displacement": 4.0,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 21,
      "make": "ford",
      "model": "explorer",
      "transmission": "a",
      "year": 2002
    },
    {
      "city_mpg": 15,
      "class": "pickup truck",
      "combination_mpg": 18,
      "cylinders": 8,
      "displacement": 5.4,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 20,
      "make": "ford",
      "model": "f-150",
      "transmission": "a",
      "year": 2001
    },
    {
      "city_mpg": 17,
      "class": "sports car",
      "combination_mpg": 20,
      "cylinders": 8,
      "displacement": 4.6,
      "drive": "rwd",
      "fuel_type": "gas",
      "highway_mpg": 26,
      "make": "ford",
      "model": "mustang",
      "transmission": "m",
      "year": 2000
    },
    {
      "city_mpg": 23,
      "class": "compact car",
      "combination_mpg": 26,
      "cylinders": 4,
      "displacement": 1.8,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 33,
      "make": "chevrolet",
      "model": "cruze",
      "transmission": "a",
      "year": 2005
    },
    {
      "city_mpg": 18,
      "class": "midsize car",
      "combination_mpg": 22,
      "cylinders": 4,
      "displacement": 2.4,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 30,
      "make": "chevrolet",
      "model": "malibu",
      "transmission": "a",
      "year": 2004
    },
    {
      "city_mpg": 20,
      "class": "compact SUV",
      "combination_mpg": 23,
      "cylinders": 4,
      "displacement": 2.4,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 28,
      "make": "chevrolet",
      "model": "equinox",
      "transmission": "a",
      "year": 2006
    },
    {
      "city_mpg": 14,
      "class": "pickup truck",
      "combination_mpg": 17,
      "cylinders": 8,
      "displacement": 5.3,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 19,
      "make": "chevrolet",
      "model": "silverado",
      "transmission": "a",
      "year": 2003
    },
    {
      "city_mpg": 16,
      "class": "sports car",
      "combination_mpg": 19,
      "cylinders": 8,
      "displacement": 6.0,
      "drive": "rwd",
      "fuel_type": "gas",
      "highway_mpg": 24,
      "make": "chevrolet",
      "model": "corvette",
      "transmission": "m",
      "year": 2001
    },
    {
      "city_mpg": 26,
      "class": "compact car",
      "combination_mpg": 30,
      "cylinders": 4,
      "displacement": 1.8,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 38,
      "make": "nissan",
      "model": "sentra",
      "transmission": "a",
      "year": 2007
    },
    {
      "city_mpg": 22,
      "class": "midsize car",
      "combination_mpg": 25,
      "cylinders": 4,
      "displacement": 2.5,
      "drive": "fwd",
      "fuel_type": "gas",
      "highway_mpg": 32,
      "make": "nissan",
      "model": "altima",
      "transmission": "a",
      "year": 2006
    },
    {
      "city_mpg": 23,
      "class": "compact SUV",
      "combination_mpg": 26,
      "cylinders": 4,
      "displacement": 2.5,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 30,
      "make": "nissan",
      "model": "rogue",
      "transmission": "a",
      "year": 2008
    },
    {
      "city_mpg": 13,
      "class": "pickup truck",
      "combination_mpg": 16,
      "cylinders": 8,
      "displacement": 5.6,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 18,
      "make": "nissan",
      "model": "titan",
      "transmission": "a",
      "year": 2005
    },
    {
      "city_mpg": 18,
      "class": "sports car",
      "combination_mpg": 21,
      "cylinders": 6,
      "displacement": 3.7,
      "drive": "rwd",
      "fuel_type": "gas",
      "highway_mpg": 25,
      "make": "nissan",
      "model": "370z",
      "transmission": "m",
      "year": 2009
    },
    {
      "city_mpg": 20,
      "class": "compact car",
      "combination_mpg": 24,
      "cylinders": 4,
      "displacement": 2.0,
      "drive": "rwd",
      "fuel_type": "gas",
      "highway_mpg": 33,
      "make": "bmw",
      "model": "3 series",
      "transmission": "m",
      "year": 2007
    },
    {
      "city_mpg": 18,
      "class": "midsize car",
      "combination_mpg": 22,
      "cylinders": 6,
      "displacement": 3.0,
      "drive": "rwd",
      "fuel_type": "gas",
      "highway_mpg": 29,
      "make": "bmw",
      "model": "5 series",
      "transmission": "a",
      "year": 2009
    },
    {
      "city_mpg": 17,
      "class": "compact SUV",
      "combination_mpg": 20,
      "cylinders": 6,
      "displacement": 3.0,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 24,
      "make": "bmw",
      "model": "x3",
      "transmission": "a",
      "year": 2010
    },
    {
      "city_mpg": 15,
      "class": "midsize SUV",
      "combination_mpg": 18,
      "cylinders": 8,
      "displacement": 4.4,
      "drive": "4wd",
      "fuel_type": "gas",
      "highway_mpg": 21,
      "make": "bmw",
      "model": "x5",
      "transmission": "a",
      "year": 2008
    },
    {
      "city_mpg": 19,
      "class": "sports car",
      "combination_mpg": 23,
      "cylinders": 6,
      "displacement": 3.0,
      "drive": "rwd",
      "fuel_type": "gas",
      "highway_mpg": 28,
      "make": "bmw",
      "model": "z4",
      "transmission": "m",
      "year": 2011
    }
    ]
  